name: CI

on: [push]

jobs:
  container:
    name: Build and publish docker container
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login
        run: docker login ghcr.io -u bahlo -p "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Build and publish docker latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t ghcr.io/bahlo/mapdns:latest .
          docker push ghcr.io/bahlo/mapdns:latest
